package com.example.communication_super_app.edition

import android.annotation.SuppressLint
import android.content.Context
import android.provider.Settings
import android.util.Log
import io.flutter.plugin.common.MethodChannel

/**
 * The device identity the inter-organizational activation code is bound to.
 *
 * Only the raw `ANDROID_ID` crosses the channel; the device code shown to the
 * user and the activation check are derived from it in Dart
 * (`ActivationCode`), so the one piece of logic that must agree with the
 * mentor's Windows generator lives in one place and is unit-tested there.
 *
 * `ANDROID_ID` needs no permission. Since Android 8 it is scoped to the
 * (signing key, user, device) triple — the commercial and organization builds
 * share a key, so they see the same value — and it is regenerated by a factory
 * reset, which is why an activation does not survive one.
 */
class DeviceIdentityHandler(private val context: Context) {
    companion object {
        const val CHANNEL = "com.example.communication_super_app/device_identity"
        private const val TAG = "DeviceIdentityHandler"
    }

    fun setup(channel: MethodChannel) {
        channel.setMethodCallHandler { call, result ->
            when (call.method) {
                "androidId" -> result.success(androidId())
                else -> result.notImplemented()
            }
        }
    }

    /** Null when the platform has none to give — never an empty string. */
    @SuppressLint("HardwareIds") // The whole point: an id bound to this device.
    private fun androidId(): String? = try {
        Settings.Secure.getString(context.contentResolver, Settings.Secure.ANDROID_ID)
            ?.trim()
            ?.takeIf { it.isNotEmpty() }
    } catch (e: Exception) {
        Log.e(TAG, "ANDROID_ID unreadable: ${e.message}")
        null
    }
}
